title: Hacker-Blog
description: "My personal blog here on GitHub"
author:
  name: "LordBlacky"
  email: "-"
  url: "https://lordblacky.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "LordBlacky"
year : "2024"
