theme: jekyll-theme-hacker
title: LordBlacky's Personal Tech-Blog
description: This is my peronal Blog where I will upload posts on different tech-topics in the future, but also on some cool things, I discover!
